CREATE TABLE PRODUCAO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idAPI INT NOT NULL
);

CREATE TABLE USUARIO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    senha VARCHAR(255) NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    pathImg VARCHAR(255)
);

CREATE TABLE TAG (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    idUsu INT NOT NULL,
    FOREIGN KEY (idUsu) REFERENCES USUARIO (id) ON DELETE CASCADE
);

CREATE TABLE LISTA (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    idUsu INT NOT NULL,
    FOREIGN KEY (idUsu) REFERENCES USUARIO (id) ON DELETE RESTRICT
);

CREATE TABLE AVALIA_PRODUCAO (
    idUsu INT NOT NULL,
    idProd INT NOT NULL,
    porcentagemAvaliacao DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (idUsu, idProd),
    FOREIGN KEY (idUsu) REFERENCES USUARIO (id) ON DELETE RESTRICT,
    FOREIGN KEY (idProd) REFERENCES PRODUCAO (id) ON DELETE RESTRICT
);

CREATE TABLE ACESSA_PRODUCAO (
    idUsu INT NOT NULL,
    idProd INT NOT NULL,
    dataHora TIMESTAMP NOT NULL,
    PRIMARY KEY (idUsu, idProd),
    FOREIGN KEY (idUsu) REFERENCES USUARIO (id) ON DELETE RESTRICT,
    FOREIGN KEY (idProd) REFERENCES PRODUCAO (id) ON DELETE RESTRICT
);

CREATE TABLE ACESSA_TAG (
    idUsu INT NOT NULL,
    idTag INT NOT NULL,
    dataHora TIMESTAMP NOT NULL,
    PRIMARY KEY (idUsu, idTag),
    FOREIGN KEY (idUsu) REFERENCES USUARIO (id) ON DELETE RESTRICT,
    FOREIGN KEY (idTag) REFERENCES TAG (id) ON DELETE SET NULL
);

CREATE TABLE PRODUCAO_TAG (
    idProd INT NOT NULL,
    idTag INT NOT NULL,
    PRIMARY KEY (idProd, idTag),
    FOREIGN KEY (idProd) REFERENCES PRODUCAO (id) ON DELETE RESTRICT,
    FOREIGN KEY (idTag) REFERENCES TAG (id) ON DELETE SET NULL
);

CREATE TABLE FAVORITA_TAG (
    idUsu INT NOT NULL,
    idTag INT NOT NULL,
    PRIMARY KEY (idUsu, idTag),
    FOREIGN KEY (idUsu) REFERENCES USUARIO (id) ON DELETE SET NULL,
    FOREIGN KEY (idTag) REFERENCES TAG (id) ON DELETE SET NULL
);

CREATE TABLE PRODUCAO_LISTA (
    idProd INT NOT NULL,
    idLista INT NOT NULL,
    PRIMARY KEY (idProd, idLista),
    FOREIGN KEY (idProd) REFERENCES PRODUCAO (id) ON DELETE RESTRICT,
    FOREIGN KEY (idLista) REFERENCES LISTA (id) ON DELETE SET NULL
);
